name: 'GitHub Mirror'

on: [ push, delete, create ]

jobs:
  mirror_to_gitee:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
#       - name: 'Mirror to gitee'
#         uses: pixta-dev/repository-mirroring-action@v1
#         with:
#           target_repo_url:
#             git@gitee.com:zhuyanzhen1/mini-foc.git
#           ssh_private_key:
#             ${{ secrets.GITEE_KEY }}
